export const subjects = {
  acsc: 'Actuarial Science',
  anat: 'Anatomy',
  arch: 'Architecture',
  assc: 'Arts & Social Sciences',
  bioc: 'Biochem & Molecular Biology',
  bioe: 'Biological Engineering',
  biol: 'Biology',
  bmng: 'Biomedical Engineering',
  buss: 'Business',
  busi: 'Business Admin',
  cana: 'Canadian Studies',
  cnlt: 'Centre for Learning & Teaching',
  chee: 'Chemical Engineering',
  chem: 'Chemistry',
  chin: 'Chinese',
  civl: 'Civil Engineering',
  clas: 'Classics',
  comm: 'Commerce',
  cmsd: 'Communication Sci & Disorders',
  chae: 'Community Health & Epidemiology',
  cpst: 'Complementary Studies',
  csci: 'Computer Science',
  ctmp: 'Contemporary Studies',
  crwr: 'Creative Writing',
  dehy: 'Dental Hygiene',
  dent: 'Dentistry',
  dmut: 'Diag Med Ultrasound Tech',
  dgin: 'Digital Innovation',
  emsp: 'Early Modern Studies',
  erth: 'Earth Sciences',
  econ: 'Economics',
  eced: 'Electrical & Computer Engineer',
  ecmm: 'Electronic Commerce',
  engi: 'Engineering',
  inwk: 'Engineering Internetworking',
  engm: 'Engineering Mathematics',
  engl: 'English',
  ensl: 'English Language (CE)',
  enve: 'Environmental Engineering',
  envs: 'Environmental Science',
  envi: 'Environmental Studies',
  euro: 'European Studies',
  film: 'Film Studies',
  figs: 'First Year Interest Groups-Sci',
  fosc: 'Food Science',
  free: 'Free Elective',
  fren: 'French',
  gwst: "Gender & Women's Studies",
  geog: 'Geography',
  germ: 'German',
  hesa: 'Health Administration',
  hinf: 'Health Informatics',
  hlth: 'Health Professions',
  hpro: 'Health Promotion',
  hsce: 'Health Sciences Education',
  hahp: 'Health and Human Performance',
  hstc: 'Hist of Science & Technology',
  hist: 'History',
  indg: 'Indigenous Studies',
  ieng: 'Industrial Engineering',
  info: 'Information Management',
  inte: 'Interdisc Studies (Graduate)',
  intd: 'International Develop Studies',
  iphe: 'Interprofessional Health Educ',
  ital: 'Italian',
  jphd: 'Joint PhD',
  jour: 'Journalism',
  kine: 'Kinesiology',
  laws: 'Law',
  ljso: 'Law, Justice, and Society',
  leis: 'Leisure Studies',
  mrit: 'Magnetic Resonance Imag Tech',
  mgmt: 'Management',
  mara: 'Marine Affairs',
  mari: 'Marine Biology',
  matl: 'Materials Engineering',
  math: 'Mathematics',
  mech: 'Mechanical Engineering',
  mdlt: 'Medical Lab Technology',
  mnsc: 'Medical Neuroscience',
  medp: 'Medical Physics',
  medr: 'Medical Research',
  mici: 'Microbiology & Immunology',
  mine: 'Mineral Resource Engineering',
  musc: 'Music',
  nesc: 'Neuroscience',
  numt: 'Nuclear Medicine Technology',
  nurs: 'Nursing',
  occu: 'Occupational Therapy',
  ocea: 'Oceanography',
  oral: 'Oral Surgery',
  phdp: 'PHD Program',
  path: 'Pathology',
  perf: 'Performance Studies',
  peri: 'Periodontics',
  phac: 'Pharmacology',
  phar: 'Pharmacy',
  phil: 'Philosophy',
  phyc: 'Physics & Atmospheric Science',
  phyl: 'Physiology',
  phyt: 'Physiotherapy',
  plan: 'Planning',
  poli: 'Political Science',
  pgph: 'Post-Graduate Pharmacy',
  peas: 'Process Engineering & App Scie',
  psyr: 'Psychiatry',
  psyo: 'Psychology',
  puad: 'Public Administration',
  radt: 'Radiological Technology',
  rels: 'Religious Studies',
  rspt: 'Respiratory Therapy',
  rusn: 'Russian Studies',
  scie: 'Science',
  slwk: 'Social Work',
  sosa: 'Sociol & Social Anthropology',
  span: 'Spanish & Latin American Stud',
  stat: 'Statistics',
  sust: 'Sustainability',
  thea: 'Theatre',
  typr: 'Transition Year Program',
  visc: 'Vision Science',
}

export const publicPaths = ['/', '/auth/signin', '/auth/signup']
